/**
 * Default categorization rules. Evaluated in order, first match wins, after
 * bank signals and transfer detection. Patterns are case-insensitive regexes.
 * Field "merchant" is the normalized merchant key (see normalize/merchant.ts).
 *
 * Convention: `brands(...)` anchors each name at the start of the merchant,
 * `words(...)` matches anywhere. Both may be combined.
 */
export type RuleField =
  | "merchant"
  | "description"
  | "counterparty"
  | "message"
  | "bank_type"
  | "bank_subtype"
  | "any";

export type SeedRule = {
  name: string;
  field: RuleField;
  pattern: string;
  category: string;
};

const brands = (...names: string[]) => `^(${names.join("|")})`;
const words = (...names: string[]) => `(${names.join("|")})`;
const either = (...patterns: string[]) => patterns.join("|");
const r = (
  name: string,
  category: string,
  pattern: string,
  field: RuleField = "merchant",
): SeedRule => ({ name, field, pattern, category });

export const SEED_RULES: SeedRule[] = [
  // Housing
  r(
    "Fellesutgifter",
    "housing:fees",
    words("BORETTSLAG", "SAMEIE", "\\bOBOS\\b", "\\bUSBL\\b"),
  ),
  r(
    "Fellesutgifter (melding)",
    "housing:fees",
    words("FELLESUTG", "FELLESKOST", "HUSLEIE"),
    "message",
  ),
  r(
    "Strøm",
    "housing:electricity",
    brands(
      "ELVIA",
      "TIBBER",
      "HAFSLUND",
      "FJORDKRAFT",
      "FORTUM",
      "NORGESENERGI",
      "LYSE\\b",
      "GUDBRANDSDAL ENERGI",
    ),
  ),
  r(
    "Lagring og håndverkere",
    "housing:other",
    either(
      brands("GREEN STORAGE", "SKANSEN ELEKTRO", "CITY SELF-STORAGE"),
      words("RØRLEGGER", "ELEKTRIKER", "MINILAGER", "FLYTTEBYRÅ"),
    ),
  ),

  // Fixed
  r("Studielån", "loans:student", brands("LÅNEKASSEN")),
  r(
    "Forsikring",
    "insurance",
    either(
      brands(
        "GJENSIDIGE FORSIKRING",
        "STOREBRAND",
        "IF SKADEFORSIKRING",
        "\\bIF\\b",
        "TRYG",
        "FREMTIND",
        "FRENDE",
        "CODAN",
        "FORSIKRINGSAKTI",
        "EIKA FORSIKRING",
      ),
      words("FORSIKRING"),
    ),
  ),
  r("Forsikring (melding)", "insurance", words("FORSIKRING"), "message"),
  r(
    "Fagforening og medlemskap",
    "membership",
    either(
      brands(
        "TEKNA",
        "NITO",
        "\\bLO\\b",
        "FAGFORBUNDET",
        "AKADEMIKERNE",
        "ECONA",
        "JURISTFORBUNDET",
        "NATURVITERNE",
        "SAMFUNNSVITERNE",
        "UTDANNINGSFORBUNDET",
      ),
      words("MEDLEMSKONTINGENT", "FAGFORENING"),
    ),
  ),
  r(
    "Veldedighet",
    "donations",
    either(
      brands(
        "SOS-BARNEBYER",
        "FLYKTNINGHJELPEN",
        "NOAH",
        "UNICEF",
        "LEGER UTEN GRENSER",
        "REDD BARNA",
        "AMNESTY",
        "RØDE KORS",
        "KIRKENS BYMISJON",
        "PLAN NORGE",
        "WWF",
        "NATURVERNFORBUNDET",
        "DYREBESKYTTELSEN",
        "GREENPEACE",
        "KREFTFORENINGEN",
        "CARE NORGE",
        "NOVARA MEDIA",
        "WIKIMEDIA",
      ),
      words("DONATION", "GAVE TIL"),
    ),
  ),
  r(
    "Skatt",
    "taxes",
    either(
      brands(
        "SKATTEETATEN",
        "SKATTEOPPKREVER",
        "KEMNER",
        "STATENS INNKREVINGSSENTRAL",
        "INNKREVINGSMYNDIGHET",
        "BÆRUM POLITISTA",
        "POLITIET",
      ),
      words("INNKREVINGSETATEN", "SKATTEETATEN", "^SKATT\\b"),
    ),
  ),
  r(
    "Inkasso og purregebyr",
    "fees",
    words("INKASSO", "PURREGEBYR", "KREDINOR", "INTRUM"),
  ),
  r(
    "Bankgebyr",
    "fees",
    either(
      brands("OMKOSTNINGER", "KORTPRODUKTER", "GEBYR"),
      words("ÅRSGEBYR", "TRANSGEBYR", "SMS VARSLING"),
    ),
    "any",
  ),

  // Subscriptions & digital
  r(
    "Streaming og digitale abonnementer",
    "subscriptions",
    brands(
      "SPOTIFY",
      "NETFLIX",
      "APPLE",
      "GOOGLE",
      "OPENAI",
      "ANTHROPIC",
      "PATREON",
      "SOUNDCLOUD",
      "CLEANSHOT",
      "PADDLE",
      "EXCALIDRAW",
      "PLUS\\.EXCALIDRAW",
      "GITHUB",
      "NOTION",
      "EGGHEAD",
      "HBO",
      "HELP\\.MAX\\.COM",
      "MAX\\b",
      "VIAPLAY",
      "DISNEY",
      "TV 2",
      "AFTENPOSTEN",
      "MORGENBLADET",
      "DAGENS NÆRINGSLIV",
      "\\bDN\\b",
      "SCHIBSTED",
      "ADOBE",
      "MICROSOFT",
      "DROPBOX",
      "1PASSWORD",
      "ICLOUD",
      "YOUTUBE",
      "TWITCH",
      "KINDLE",
      "AUDIBLE",
      "STORYTEL",
      "DUOLINGO",
      "STRAVA",
      "SETAPP",
      "JETBRAINS",
      "RAYCAST",
      "FIGMA",
      "VERCEL",
      "FLY\\.IO",
      "DIGITALOCEAN",
      "HETZNER",
      "CLOUDFLARE",
      "NAMECHEAP",
      "DOMENESHOP",
      "CURSOR",
      "SUPERHUMAN",
      "READWISE",
      "OBSIDIAN",
      "PROTON",
      "FASTMAIL",
      "TIDAL",
      "NRK",
      "PODIMO",
      "MEDIUM\\.COM",
      "SUBSTACK",
      "NYTIMES",
      "THE ECONOMIST",
      "STEPHEN WELCH TUTORING",
      "SKILLSHARE",
      "COURSERA",
      "UDEMY",
      "MUBI",
      "PRIME VIDEO",
      "HBO MAX",
      "USE\\.AI",
      "ONE\\.COM",
      "MIMEO",
      "RIKSTV",
      "STRIM\\b",
      "INFORMATION ARCHITECTS",
      "ZED\\b",
      "OURARING",
      "OURA\\b",
      "REFLECT\\.APP",
      "MASTERCLASS",
      "LINEAR\\b",
      "ARC\\b",
      "KAGI",
      "PERPLEXITY",
      "MIDJOURNEY",
      "ELEVENLABS",
      "REPLICATE",
      "HUGGINGFACE",
      "TAILSCALE",
      "BACKBLAZE",
      "GOOGLE ONE",
      "WHOOP",
      "HEADSPACE",
      "CALM\\b",
      "BITWARDEN",
      "PLAUSIBLE",
      "SENTRY",
    ),
  ),
  r(
    "Mobil og bredbånd",
    "subscriptions",
    brands(
      "TELIA",
      "TELENOR",
      "\\bICE\\b",
      "CHILIMOBIL",
      "TALKMORE",
      "ONECALL",
      "MYCALL",
      "FJORDKRAFT MOBIL",
      "HOMENET",
      "GLOBALCONNECT",
      "ALTIBOX",
      "NEXTGENTEL",
    ),
  ),

  // Food
  r(
    "Kantine",
    "dining:canteen",
    brands(
      "KANTINE",
      "4SERVICE",
      "EUREST",
      "ISS FACILITY",
      "COMPASS GROUP",
      "SODEXO",
      "ØKERN PORTAL",
    ),
  ),
  r(
    "Dagligvarer",
    "groceries",
    either(
      brands(
        "JOKER",
        "COOP",
        "REMA 1000",
        "MENY",
        "KIWI",
        "BUNNPRIS",
        "MATKROKEN",
        "SPAR\\b",
        "EUROPRIS",
        "JACOBS",
        "ULTRA\\b",
        "HOLDBART",
        "NÆRBUTIKKEN",
        "MATVAREEXPRESSEN",
        "ODA\\b",
        "KOLONIAL",
        "EXTRA\\b",
        "OBS\\b",
        "PRIX\\b",
        "GRØNLAND BASAR",
        "ANNIS PØLSEMAKE",
        "ANNIS POLSEMAKE",
        "SMAK AV ITALIA",
        "SMAKAVITALIA",
        "OSLO KOLONIAL",
        "FRUKT OG GRØNT",
        "CORDIAL AS",
        "HELIOS",
        "OSTEBUTIKKEN",
        "FISKEBUTIKKEN",
        "KROGER",
        "WM SUPERCENTER",
        "WALMART",
        "TRADER JOE",
        "WHOLE FOODS",
        "TESCO",
        "SAINSBURY",
        "LIDL",
        "ALDI",
        "NETTO",
        "IRMA",
        "FØTEX",
        "BILKA",
        "ICA\\b",
        "HEMKÖP",
        "WILLYS",
        "KOKKELOEREN",
        "KOKKELØREN",
        "FISKERIET",
        "CC MAT",
        "GODT BRØD",
        "BAKER HANSEN",
        "MATHALLEN",
      ),
      words("DAGLIGVARE", "MATBUTIKK", "KOLONIAL"),
    ),
  ),
  r(
    "Kiosk",
    "groceries",
    either(
      brands(
        "NARVESEN",
        "7-ELEVEN",
        "DELI DE LUCA",
        "MIX\\b",
        "COCA COLA",
        "SYVERKIOSKEN",
      ),
      words("KIOSK"),
    ),
  ),
  r(
    "Kafé og bakeri",
    "dining:cafe",
    either(
      brands(
        "ÅPENT BAKERI",
        "JAVA ESPRESSOBAR",
        "SUPREME ROAST",
        "BRYGG\\b",
        "COPENHAGEN COFFEE",
        "EMMAS BAGELS",
        "LA BAKERI",
        "KAFFEBRENNERIET",
        "STOCKFLETHS",
        "ESPRESSO HOUSE",
        "W B SAMSON",
        "SAMSON",
        "TIM WENDELBOE",
        "FUGLEN",
        "STEAM KAFFEBAR",
        "BIT\\b",
        "DROPSEN",
        "PASCAL",
        "UTECAFE",
        "JOE THE JUICE",
        "JOE & THE JUICE",
        "BACKSTUBE",
        "FRIDA BAKERY",
        "LILLEHAMMER BAKERI",
        "LILLE OSLO KAFFE",
        "STARBUCKS",
        "PRET A MANGER",
        "PRET\\b",
        "GRØDBAREN",
        "TALORMADE",
        "GODT BRØD",
        "BAKER HANSEN",
        "UNITED BAKERIES",
      ),
      words(
        "CAFE",
        "KAFE",
        "KAFÉ",
        "COFFEE",
        "KAFFE",
        "BAKERI",
        "BAKERY",
        "BAGEL",
        "BAKER\\b",
        "ESPRESSO",
        "KONDITORI",
      ),
    ),
  ),
  r(
    "Restaurant og bar",
    "dining:restaurant",
    either(
      brands(
        "SAGENE BRYGGERI",
        "ANGSTBAR",
        "TUNCO",
        "HAKONE",
        "PEPPES",
        "SALT\\b",
        "ONKEL WAHEED",
        "LUSH DIVE",
        "GUTTA DRIFT",
        "JORD\\b",
        "VAAR AS",
        "FOY AS",
        "BYENS TAK",
        "BABBO",
        "NORDIC CROWN",
        "BRUS\\b",
        "VIPPA",
        "OSLO STREET FOOD",
        "VILLA PARADISO",
        "LOFTHUS SAMVIRKELAG",
        "HITCHHIKER",
        "OLYMPEN",
        "SCHOUS",
        "CITY SLICE",
        "EVVIVA",
        "FAVRIT",
        "MCDONALDS",
        "BURGER KING",
        "MAX BURGER",
        "ST\\.? ?PAULI BIER",
        "MAALTID",
        "SMALHANS",
        "KOLONIHAGEN",
        "CAFE SARA",
        "OSLO MEKANISKE",
        "CROWBAR",
        "HIMKOK",
        "TORGGATA BOTANISKE",
        "MAAEMO",
        "KONTRAST",
        "SENTRALEN",
        "BASS OSLO",
        "TAKEAWAY",
        "NIGHTHAWK",
        "EIFFELTÅRNET",
        "EL TESORO",
        "FREYBORGSTUA",
        "KONSTABEL",
        "GRISEN",
        "SKAAL",
        "SPORTSBAR",
        "9 MILE STATION",
        "ROTTER",
        "MANOIR",
        "DA LAURA",
        "GL HAUSSMANN",
        "CAFE TAARNET",
        "MAMOUNIA",
        "VULKANFISK",
        "VEGA SNACKBAR",
        "TXOTX",
        "KHANATERIA",
        "AMBASSADEN",
        "MARSTANG",
        "LA MEDITERRANEE",
        "HEIM ST",
        "POKALEN",
        "COUSINS",
        "TIFFANI",
        "REFFEN",
        "GRAINS",
      ),
      words(
        "PIZZA",
        "RESTAURA",
        "RESTO\\b",
        "SUSHI",
        "BURGER",
        "KEBAB",
        "GRILL",
        "BISTRO",
        "BRASSERIE",
        "TRATTORIA",
        "OSTERIA",
        "TAQUERIA",
        "RAMEN",
        "THAI\\b",
        "\\bBAR\\b",
        "\\bPUB\\b",
        "BRYGGERI",
        "BREWERY",
        "VINBAR",
        "IZAKAYA",
        "DINNER",
        "MEZE",
        "TAPAS",
        "GASTROPUB",
        "SPISERI",
        "\\bKRO\\b",
        "CANTINA",
        "DIVE\\b",
        "BIER\\b",
        "BEER\\b",
        "WINE\\b",
        "COCKTAIL",
        "NOODLE",
        "DUMPLING",
        "TACO",
      ),
    ),
  ),
  r(
    "Takeaway og levering",
    "dining:delivery",
    brands("WOLT", "FOODORA", "JUST EAT", "UBER EATS"),
  ),
  r(
    "Vinmonopolet",
    "alcohol",
    either(
      brands("VINMONOPOLET", "VIN OSLO", "SYSTEMBOLAGET"),
      words("VINMONOPOL"),
    ),
  ),

  // Transport
  r(
    "Kollektivtransport",
    "transport:public",
    brands(
      "RUTER",
      "VY",
      "FLYTOGET",
      "ENTUR",
      "FLYBUSSEN",
      "SJ\\b",
      "SKYSS",
      "ATB\\b",
      "KOLUMBUS",
      "BRAKAR",
      "NSB",
      "METRO SERVICE",
      "FLIXBUS",
      "OMIO",
      "TRAINLINE",
      "DSB\\b",
      "EUROSTAR",
      "DEUTSCHE BAHN",
      "DB VERTRIEB",
      "SNCF",
      "RENFE",
      "TRENITALIA",
      "NS\\.NL",
      "MTA\\b",
      "TFL\\b",
      "BART\\b",
      "CLIPPER",
    ),
  ),
  r(
    "Sparkesykkel og bysykkel",
    "transport:micro",
    either(
      brands(
        "VOI",
        "RYDE",
        "TIER",
        "LIME",
        "OSLO BYSYKKEL",
        "OSLOBYSYKKEL",
        "BYSYKKEL",
        "DONKEY REPUBLIC",
      ),
      words("BYSYKKEL"),
    ),
  ),
  r(
    "Taxi",
    "transport:taxi",
    either(
      brands(
        "OSLO TAXI",
        "BOLT",
        "UBER",
        "NORGESTAXI",
        "CABONLINE",
        "YANGO",
        "FREE NOW",
        "LYFT",
      ),
      words("TAXI"),
    ),
  ),
  r(
    "Bil, parkering og drivstoff",
    "transport:car",
    either(
      brands(
        "HYRE",
        "EASYPARK",
        "AIMO PARK",
        "CIRCLE K",
        "ESSO",
        "SHELL",
        "UNO-X",
        "ST1",
        "FJELLINJEN",
        "AUTOPASS",
        "BOMRING",
        "AVIS",
        "HERTZ",
        "SIXT",
        "GETAROUND",
        "Q-PARK",
        "APCOA",
        "ONEPARK",
        "BILKOLLEKTIVET",
        "TESLA",
        "NAF\\b",
        "VIKING",
        "BILXTRA",
        "MEKONOMEN",
        "STATENS VEGVESEN",
        "APARK",
        "OSLOBILUTLEIE",
        "RENT-A-CAR",
        "EUROPCAR",
        "ENTERPRISE RENT",
        "PAYEX",
        "MOVE ABOUT",
        "TOLL",
      ),
      words(
        "PARKERING",
        "PARKING",
        "BOMPENGER",
        "BILUTLEIE",
        "BILVASK",
        "BENSIN",
        "DRIVSTOFF",
        "TOLL FEES",
      ),
    ),
  ),

  // Travel
  r(
    "Reise",
    "travel",
    either(
      brands(
        "AIRBNB",
        "SAS\\b",
        "NORWEGIAN",
        "WIDERØE",
        "RYANAIR",
        "KLM",
        "LUFTHANSA",
        "FINNAIR",
        "EASYJET",
        "WIZZ",
        "BRITISH AIRWAYS",
        "DELTA AIR",
        "UNITED AIR",
        "AMERICAN AIR",
        "BOOKING\\.COM",
        "HOTELS\\.COM",
        "EXPEDIA",
        "TRIP\\.COM",
        "SCANDIC",
        "THON HOTEL",
        "RADISSON",
        "CHOICE HOTELS",
        "STRAWBERRY",
        "COMFORT HOTEL",
        "CLARION",
        "QUALITY HOTEL",
        "DUTY-FREE",
        "DUTY FREE",
        "OK EJBY",
        "EUROBONUS",
        "GARDERMOEN",
        "TORP",
        "HURTIGRUTEN",
        "COLOR LINE",
        "FJORD LINE",
        "STENA LINE",
        "THE THIEF",
        "ALVINA SHIPPING",
        "NAS INFLIGHT",
        "AGGERSHOEJ",
        "VRBO",
        "HOSTELWORLD",
        "HOTEIS",
        "MARRIOTT",
        "HILTON",
        "HYATT",
        "NOVOTEL",
        "IBIS\\b",
        "CITYBOX",
        "SMARTHOTEL",
        "TRAVELODGE",
        "PREMIER INN",
        "GATE GOURMET",
        "TSA\\b",
        "AVINOR",
        "OSL\\b",
      ),
      words(
        "HOTEL",
        "HOTELL",
        "TRAVEL",
        "HOSTEL",
        "INFLIGHT",
        "AIRPORT",
        "LUFTHAVN",
        "FLYPLASS",
        "AIRLINES",
        "AIRWAYS",
        "FERRY",
        "FERGE",
      ),
    ),
  ),

  // Health & pets & kids
  r(
    "Helse og apotek",
    "health",
    either(
      brands(
        "VITUSAPOTEK",
        "APOTEK",
        "BOOTS",
        "DR\\.? ?DROPIN",
        "VOLVAT",
        "AVONOVA",
        "ALERIS",
        "SPECSAVERS",
        "BRILLELAND",
        "SYNSAM",
        "KRONA",
        "INTEROPTIK",
        "DEN NORSKE TANNLEGE",
        "SQUEEZE",
      ),
      words(
        "APOTEK",
        "\\bLEGE\\b",
        "LEGESENTER",
        "LEGEVAKT",
        "TANNLEGE",
        "TANNHELSE",
        "FYSIO",
        "KIROPRAKT",
        "OPTIKER",
        "HELSE",
        "PSYKOLOG",
        "NAPRAPAT",
        "OSTEOPAT",
        "PHARMACY",
        "CLINIC",
        "KLINIKK",
      ),
    ),
  ),
  r(
    "Kjæledyr",
    "pets",
    either(
      brands(
        "ANICURA",
        "BUSTER",
        "DOGMAN",
        "MUSTI",
        "PETXL",
        "PETS\\b",
        "ZOO ?1",
        "ARKEN ZOO",
        "EMPET",
        "EVIDENSIA",
        "DYREBUTIKK",
        "HUNDE",
      ),
      words("VETERINÆR", "DYREKLINIKK", "DYREBUTIKK", "\\bHUND\\b", "PETSHOP"),
    ),
  ),
  r(
    "Barn",
    "kids",
    either(
      brands(
        "BARNAS HUS",
        "ARTIPOPPE",
        "JOLLYROOM",
        "BABYSHOP",
        "LEKMER",
        "POLARN O\\.? PYRET",
        "BABYSAM",
        "BABYVERDEN",
        "STOKKE",
        "LEKIA",
        "TOYS",
        "SPRELL",
        "BIBS DENMARK",
        "NAJELL",
        "SNUZ",
        "GÅSUNGEN",
        "GASUNGEN",
        "SMÅ SPOR",
        "GREEN KIDS",
        "BOEFBOEF",
        "ITSKAOS",
        "LILLE KAOS",
        "BABYZEN",
        "BUGABOO",
        "MINI ?RODINI",
        "KIDSBRANDSTORE",
        "REIMA",
        "NAME IT",
        "MAERKBARE",
        "BABYPLANET",
        "BABYDAN",
        "MEDELA",
      ),
      words("BARNEHAGE", "BARNEKLÆR", "LEKER", "BABY", "BARNEVOGN", "BLEIER"),
    ),
  ),

  // Shopping & leisure
  r(
    "Hjem og oppussing",
    "shopping:home",
    either(
      brands(
        "IKEA",
        "CLAS OHLSON",
        "JYSK",
        "KID\\b",
        "PRINCESS",
        "BOHUS",
        "SKEIDAR",
        "MØBEL",
        "AAS MØBELDESIGN",
        "JERNIA",
        "MAXBO",
        "BYGGMAKKER",
        "MONTER",
        "OBS BYGG",
        "MESTERGRUPPEN",
        "ELKJØP",
        "POWER\\b",
        "KOMPLETT",
        "BILTEMA",
        "PLANTASJEN",
        "TILBORDS",
        "KITCH'?N",
        "HOME & COTTAGE",
        "H&M HOME",
        "HM HOME",
        "ILLUMS",
        "BOLIA",
        "SLETTVOLL",
        "NORDIC NEST",
        "ROYAL DESIGN",
        "SØSTRENE GRENE",
        "FLYING TIGER",
        "RUSTA",
        "BAUHAUS",
        "COOP BYGG",
        "MEGAFLIS",
        "FLISEKOMPANIET",
        "MALIA",
        "FARGERIKE",
        "LAMPEHUSET",
        "KREMMERHUSET",
        "BACH JULETRESAL",
        "NILLE",
        "CULINA",
        "GEVIR",
        "NORSK SENGESENT",
        "NORSK SENGESENTER",
        "LAYERED",
        "LAGERHAUS",
        "STUDIOBAZAR",
        "FUTAH",
        "SVOVEL DESIGN",
        "PANDURO",
        "T ENTREPRENOR",
        "EU\\.STORE\\.UI",
        "UBIQUITI",
        "DESIGNTORGET",
        "HAY\\b",
        "NORTHERN\\b",
        "MENU\\b",
        "FRITZ HANSEN",
        "LOUIS POULSEN",
        "TAPETSERER",
      ),
      words(
        "MØBLER",
        "INTERIØR",
        "JULETRE",
        "BYGGVARE",
        "TRELAST",
        "OPPUSSING",
      ),
    ),
  ),
  r(
    "Klær og sko",
    "shopping:clothes",
    either(
      brands(
        "H&M",
        "ZARA",
        "WEEKDAY",
        "MONKI",
        "COS\\b",
        "ARKET",
        "UNIQLO",
        "DRESSMANN",
        "CUBUS",
        "BIK BOK",
        "CARLINGS",
        "VOLT\\b",
        "NIKE",
        "ADIDAS",
        "XXL",
        "INTERSPORT",
        "SPORT 1",
        "G-SPORT",
        "ZALANDO",
        "BOOZT",
        "LEVI",
        "FJÄLLRÄVEN",
        "FJALLRAVEN",
        "NORRØNA",
        "BERGANS",
        "HELLY HANSEN",
        "PEAK PERFORMANCE",
        "SAMSØE",
        "SAMSOE",
        "TIGER OF SWEDEN",
        "FILIPPA K",
        "HOLZWEILER",
        "ACNE",
        "GANNI",
        "ANTON SPORT",
        "SKOTØYMAGASINET",
        "EUROSKO",
        "DNA\\b",
        "VINTAGE",
        "FRETEX",
        "UFF\\b",
        "BRANDY MELVILLE",
        "DEVOLD",
        "ULVANG",
        "STORMBERG",
        "BUNAD",
        "FERNER JACOBSEN",
        "ENSEMBLE",
        "KLATTERMUSEN",
        "KLÄTTERMUSEN",
        "OSLO SPORTSLAGER",
        "DAPPER",
        "SELFMADE",
        "STEEN & STRØM",
        "VERO MODA",
        "MANGO\\b",
        "BELLROY",
        "GLOBAL RETAIL GROUP",
        "KAPPAHL",
        "GINA TRICOT",
        "GRANDSENS SKOT",
        "OUTNORTH",
        "KARHU",
        "NEXT\\b",
        "LINDEX",
        "SKOTØY",
        "PATAGONIA",
        "ARC'TERYX",
        "ARCTERYX",
        "LULULEMON",
        "ON RUNNING",
        "HOKA",
        "ASICS",
        "NEW BALANCE",
        "DR\\.? MARTENS",
        "VAGABOND",
        "SWIMS",
        "SNEAKERS",
        "CAPPELEN DAMM",
      ),
      words("KLÆR", "CLOTHING", "FASHION", "\\bSKO\\b", "SHOES"),
    ),
  ),
  r(
    "Frisør og velvære",
    "personal_care",
    either(
      brands(
        "CUTTERS",
        "KICKS",
        "VITA\\b",
        "NORMAL\\b",
        "LUSH\\b",
        "AESOP",
        "BRUN OG BLID",
        "SQUEEZE",
        "SEPHORA",
        "BOOTS APOTEK",
      ),
      words(
        "FRISØR",
        "FRISOR",
        "BARBER",
        "SALONG",
        "HUDPLEIE",
        "NEGL",
        "\\bSPA\\b",
        "MASSASJE",
        "BADSTU",
        "SAUNA",
      ),
    ),
  ),
  r(
    "Kultur og underholdning",
    "entertainment",
    either(
      brands(
        "BLÅ\\b",
        "BLA /",
        "PARKTEATRET",
        "ROCKEFELLER",
        "SENTRUM SCENE",
        "VULKAN ARENA",
        "CINEMATEKET",
        "DEICHMAN",
        "NORLI",
        "TANUM",
        "TRONSMO",
        "ARK\\b",
        "PLATEKOMPANIET",
        "BIG DIPPER",
        "SYNG\\b",
        "STEAM\\b",
        "PLAYSTATION",
        "NINTENDO",
        "XBOX",
        "TICKETMASTER",
        "BILLETTSERVICE",
        "TIKKIO",
        "HOOPLA",
        "NORDISK FILM",
        "ODEON",
        "MUNCH",
        "NASJONALMUSEET",
        "ASTRUP",
        "VIGELAND",
        "TUSENFRYD",
        "ØYAFESTIVALEN",
        "DEN NORSKE OPERA",
        "VEGA SCENE",
        "DRAMMEN SCENER",
        "PISTOLSTRÆDE",
        "REVOLVER",
        "INGENSTEDS",
        "JAEGER",
        "JÆGER",
        "KULTURHUSET",
        "SALT ART",
        "GOLDIE",
        "ROCKEFELLER",
        "CHATEAU NEUF",
        "OSLO KONSERTHUS",
        "OPERAEN",
      ),
      words(
        "KINO",
        "TEATER",
        "THEATRE",
        "OPERA\\b",
        "KONSERT",
        "CONCERT",
        "MUSEUM",
        "FESTIVAL",
        "BOWLING",
        "ESCAPE ROOM",
        "GALLERI",
        "GALLERY",
        "BOKHANDEL",
        "KARAOKE",
        "QUIZ",
        "TICKETS",
        "BILLETT",
      ),
    ),
  ),
  r(
    "Trening og fritid",
    "sports",
    either(
      brands(
        "SATS",
        "ELIXIA",
        "FRESH FITNESS",
        "EVO\\b",
        "3T\\b",
        "BARRYS",
        "CROSSFIT",
        "OSLO BADSTUFORENING",
        "OSLO KLATRESENTER",
        "SKIFORENINGEN",
        "TØYENBADET",
        "FROGNERBADET",
        "TJØTTA",
        "PELOTON",
        "NYE PELOTON",
        "FOMOTO",
        "FINNPIKLER",
      ),
      words(
        "TRENING",
        "FITNESS",
        "IDRETT",
        "BADSTUFOREN",
        "SVØMME",
        "KLATRING",
        "YOGA",
        "PILATES",
        "GOLF",
        "TENNIS",
        "PADEL",
        "SKI\\b",
        "SYKKEL",
      ),
    ),
  ),
  r(
    "Blomster og gaver",
    "gifts",
    either(
      brands(
        "INTERFLORA",
        "MESTER GRØNN",
        "EUROFLORIST",
        "FINN BLOMSTER",
        "BABETTE GULDSMEDEN",
        "DAVID-ANDERSEN",
        "THUNE",
        "BJØRKLUND",
      ),
      words("BLOMST", "GAVEKORT", "GULDSMED", "GULLSMED", "RIKKES HAGE"),
    ),
  ),
  r(
    "Elektronikk og annet",
    "shopping:other",
    either(
      brands(
        "SCANDINAVIAN PH",
        "TARGET",
        "WALGREENS",
        "THE LIGHT PHONE",
        "AMAZON",
        "EBAY",
        "ETSY",
        "TEMU",
        "SHEIN",
        "WISH\\b",
        "ALIEXPRESS",
        "APPLE STORE",
        "EPLEHUSET",
        "KJELL & CO",
        "KJELL\\b",
        "TEKNIKMAGASINET",
        "FOTO\\b",
        "JAPAN PHOTO",
        "POSTEN",
        "POSTNORD",
        "BRING\\b",
        "HELTHJEM",
        "POSTNL",
        "DHL",
        "UPS\\b",
        "FEDEX",
        "VINTED",
        "FINN\\.NO",
        "TISE",
      ),
      words("ELEKTRO", "FOTO"),
    ),
  ),
  r(
    "Kontantuttak",
    "cash",
    words("KONTANTUTTAK", "MINIBANK", "\\bATM\\b", "\\bCASH\\b"),
    "any",
  ),

  // Generic person-to-person signals (after merchants)
  r("Vipps til personer", "people", "^Vipps\\*|^Vipps$", "description"),
  r("Vipps uten mottaker", "people", "^VIPPS$"),
  r(
    "Straksbetaling til/fra personer",
    "people",
    "^(Straksutbetaling|Straksinnbetaling|Straksbetaling|immediate)$",
    "bank_type",
  ),
  r(
    "Betaling med melding",
    "people",
    "^(Utgående betaling med melding|Innkommende betaling med melding|Straksbetaling|Utgående betaling|Betaling internasjonal)$",
    "bank_subtype",
  ),
  r(
    "Innkommende overføring",
    "income:other",
    "^(Overføring fra annen konto|Innkommende betaling)$",
    "bank_subtype",
  ),
  r("Giro inn", "income:other", "^Giro$", "bank_type"),
];
